personal_webpage/parent_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as parent_site_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

# from django.urls import reverse_lazy
# app_name = "parent_site"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contact/", parent_site_views.contact, name="contact"),
    # apps
    path("portfolio/", include("portfolio.urls", namespace="portfolio")),
    path("users/", include("users.urls", namespace="users")),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
    ),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_webpage/portfolio/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views as portfolio_views
from .views import ProjectListView, ProjectDetailView


app_name = "portfolio"
urlpatterns = [
    path("", portfolio_views.about, name="about"),
    # path("about/", portfolio_views.about, name="about"),
    path("contact/", portfolio_views.contact, name="contact"),
    path("projects", ProjectListView.as_view(), name="projects"),
    path("project/<int:pk>/", ProjectDetailView.as_view(), name="project")
    # path("single/<slug:slug>", views.single, name="single"),
]

personal_webpage/users/urls.py
from django.urls import path
from . import views as user_views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
app_name = "users"
urlpatterns = [
    path("register/", user_views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done'))
      #   ,template_name="users/password_reset.html"
        ,
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(

            template_name="users/password_reset_done.html"
        ),
        name="password-reset-done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('users:password_reset_complete'),
             template_name="users/password_reset_confirm.html"
        ),
        name="password-reset-confirm"),
#     path(
#         'reset_password/',
#         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')),
#         name='reset_password'
#     ),
#     path(
#         'reset_password_sent/',
#         auth_views.PasswordResetDoneView.as_view(),
#         name='password_reset_done'
#     ),
#     path(
#         'reset/<uidb64>/<token>/',
#         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('users:password_reset_complete')),
#         name='password_reset_confirm'
#     ),
#     path(
#         'reset_password_complete/',
#         auth_views.PasswordResetCompleteView.as_view(),
#         name='password_reset_complete'
#     ),

    path("profile/", user_views.profile, name="profile"),
]
# path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),

personal_webpage/parent_site/views.py
from django.shortcuts import render



def contact(request):
  return render(request, "parent_site_contact.html", {})

personal_webpage/parent_site/templates/parent_site_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href={% static "portfolio.css" %}>
    <!-- <link rel="stylesheet" type="text/css" href={% static "home_site.css" %}> -->
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
  
    {% if title %}
    <title>John's Site - {{ title }}</title>
{% else %}
    <title>John's Site</title>
{% endif %}
  </head>
  <body >

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">somethang</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio:about' %}">Portfolio</a>
            </li>
    
          </ul>

          <div class="navbar-nav">
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
            {% endif %}
        </div>
      </div>
    </nav>



</nav>

    {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
    {% endif %}
    

    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

personal_webpage/parent_site/templates/parent_site_contact.html
{% extends "parent_site_base.html" %}
{% load static %}



{% block content %}


<h1>Contact</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-actions">
        <input type="text" name ="message_name" placeholder="Subject">
        <input type="email" name ="message_email" placeholder ="Your email">
        <input type="message" name ="message" placeholder ="Enter your message here">
      <button type="submit">Send</button>
    </div>
</form>



<form>
  <div class="form-group">
    <label for="exampleFormControlInput1">Email address</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Example select</label>
    <select class="form-control" id="exampleFormControlSelect1">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlSelect2">Example multiple select</label>
    <select multiple class="form-control" id="exampleFormControlSelect2">
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5</option>
    </select>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Example textarea</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
</form>

{% endblock %}

personal_webpage/parent_site/templates/password_reset_confirm.html
{% extends "parent_site_base.html" %} 
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
            </div>
        </form>
    </div>
{% endblock content %}

personal_webpage/parent_site/templates/password_reset_done.html
{% extends "parent_site_base.html" %} 
{% block content %}

    <div class="alert alert-info">
      An email with instructions on resetting your password has been sent 
    </div>
{% endblock content %}