personal_webpage/parent_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as parent_site_views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

# from django.urls import reverse_lazy
# app_name = "parent_site"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("contact/", parent_site_views.contact, name="contact"),
    # apps
    path("portfolio/", include("portfolio.urls", namespace="portfolio")),
    path("users/", include("users.urls", namespace="users")),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
    ),


]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

personal_webpage/portfolio/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views as portfolio_views
from .views import ProjectListView, ProjectDetailView


app_name = "portfolio"
urlpatterns = [
    path("", portfolio_views.about, name="about"),
    # path("about/", portfolio_views.about, name="about"),
    path("contact/", portfolio_views.contact, name="contact"),
    path("projects", ProjectListView.as_view(), name="projects"),
    path("project/<int:pk>/", ProjectDetailView.as_view(), name="project")
    # path("single/<slug:slug>", views.single, name="single"),
]

personal_webpage/users/urls.py
from django.urls import path
from . import views as user_views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
app_name = "users"
urlpatterns = [
    path("register/", user_views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done'))
      #   ,template_name="users/password_reset.html"
        ,
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(

            template_name="users/password_reset_done.html"
        ),
        name="password-reset-done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('users:password_reset_complete'),
             template_name="users/password_reset_confirm.html"
        ),
        name="password-reset-confirm"),
#     path(
#         'reset_password/',
#         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')),
#         name='reset_password'
#     ),
#     path(
#         'reset_password_sent/',
#         auth_views.PasswordResetDoneView.as_view(),
#         name='password_reset_done'
#     ),
#     path(
#         'reset/<uidb64>/<token>/',
#         auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('users:password_reset_complete')),
#         name='password_reset_confirm'
#     ),
#     path(
#         'reset_password_complete/',
#         auth_views.PasswordResetCompleteView.as_view(),
#         name='password_reset_complete'
#     ),

    path("profile/", user_views.profile, name="profile"),
]
# path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_done')), name='password_reset'),

personal_webpage/portfolio/models.py
from django.db import models
from django.utils import timezone


class Project(models.Model):
    title = models.CharField(
        max_length=100,
        null=False,
        unique=False,
        blank=False,
        # # verbose_name=_("project title"),
        # help_text=_("format: required, max-100"),
    )

    description = models.TextField(
        unique=False,
        null=False,
        # blank=False,
        # verbose_name=_("project description"),
        # help_text=_("format: required"),
    )

    description_short = models.TextField(
        max_length=1000, unique=False, null=False, default="<Not provided>"
    )
    concepts = models.TextField(
        max_length=1000,
        unique=False,
        null=True,
           blank=True,
    )

    technology = models.TextField(
        max_length=1000,
        unique=False,
        null=True,
           blank=True,
    )

    github = models.URLField(
        max_length=150,
        unique=False,
        null=False,
        blank=True,
        # verbose_name=_("github url"),
        # help_text=_("format: required"),
    )

    website = models.URLField(
        max_length=150,
        unique=False,
        null=False,
        blank=True,
        # verbose_name=_("project website"),
        # help_text=_("format: required"),
    )

    img_url = models.URLField(
        max_length=150,
        unique=False,
        null=False,
        blank=True,
        # verbose_name=_("project image url"),
        # help_text=_("format: required"),
    )

    featured = models.BooleanField(
        default=True,
        null=False,
        blank=False,
        # verbose_name=_("project image url"),
        # help_text=_("format: required"),
    )

    date_posted = models.DateTimeField(default=timezone.now)

    date_updated = models.DateTimeField(auto_now=True)

    # tags = ArrayField(models.CharField(max_length=35, blank=True))

    # date_posted = models.DateTimeField(default=timezone.now)
    # deletes all user's posts with CASCADE
    # author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ["title"]

    # added to make easier to understand
    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("project-detail", kwargs={"pk": self.pk})


# get tags list before
# if removed one of tags
# if tag has no other refs
# delete tag


# @receiver(post_save, sender=Project, dispatch_uid="delete_tags_with_no_project")
# def delete_tags_with_no_project(sender, instance, **kwargs):

# for each tag
# check if tag has other references, if not delete tag
# if not Server.objects.filter(contact=instance.contact):
#     instance.contact.delete()

# @receiver(post_delete, sender=Project, dispatch_uid="delete_tags_with_no_project")

personal_webpage/portfolio/forms.py
from django import forms


class ContactForm(forms.Form):
    email_sender_name = forms.CharField(
        required=True, max_length=255, label="Your Name"
    )
    email_subject = forms.CharField(
        required=True, max_length=255, label="Email Subject"
    )
    email_sender_email = forms.EmailField(required=True, label="Your Email")
    email_content = forms.CharField(
        required=True, widget=forms.Textarea, label="Email Content"
    )

personal_webpage/portfolio/views.py
from django.http import request
from django.shortcuts import redirect, render
from .forms import ContactForm as PortfolioContactForm
from .models import Project
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.contrib import messages

from django.conf import settings


def home(request):
    context = {"projects": Project.objects.all()}

    return render(request, "portfolio/portfolio_home.html", context)


def contact(request):
    print(settings.EMAIL_HOST_USER)
    print(settings.DEFAULT_RECEIVING_EMAIL)
    if request.method == "POST":
        form = PortfolioContactForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data

            email_sender_name = cleaned_data["email_sender_name"]
            email_subject = cleaned_data["email_subject"]
            email_sender_email = cleaned_data["email_sender_email"]
            email_content = cleaned_data["email_content"]

            try:
                send_mail(
                    f"personal website email from <{email_sender_email}> subject<{email_subject}>",
                    f"""
                    sender name: <{email_sender_name}>
                    sender email: <{email_sender_email}>
                    subject: <{email_subject}>

                    message:
                    {email_content}



    
                    """,
        
                    settings.EMAIL_HOST_USER,
                    [settings.DEFAULT_RECEIVING_EMAIL],
                )
            except:
                messages.error(
                    request,
                    "There was a problem sending your email, but your request has been logged",
                )

            messages.success(request, "Your email has been sent.")
            return HttpResponseRedirect("./")

    else:
        form = PortfolioContactForm()

    return render(request, "portfolio/portfolio_contact.html", {"form": form})


def about(request):
    # posts = Post.objects.all()
    return render(request, "portfolio/portfolio_about.html", {})


class ProjectListView(ListView):
    model = Project
    template_name = "portfolio/portfolio_projects.html"
    context_object_name = "projects"
    ordering = ["-date_posted"]
    paginate_by = 5


class ProjectDetailView(DetailView):
    model = Project
    template_name = "portfolio/portfolio_project.html"

personal_webpage/portfolio/templates/portfolio/portfolio_about.html
{% extends "portfolio/portfolio_base.html" %}
{% load static %}



{% block content %}

<div id="name-header"  class="jumbotron bg-cover text-white">
  <div id="header-name-container" class="container py-5 text-center">
      <h1 class="display-1 font-weight-bold">John Ericson</h1>
      <p class="font-italic display-4 mb-0">Software Engineer</p>


      </p>
      <a href="{% url 'portfolio:contact' %}" role="button" class="btn btn-primary px-5">Contact</a>
      <a  href="{% static 'resume_website.pdf' %}" role="button" class="btn btn-primary px-5" target="_blank" rel="noopener noreferrer">Resume</a>
  </div>
</div>



        <!-- ======= Resume Section ======= -->
        <section id="resume" class="resume">
          <div class="container">
    
     
    
            <div class="row">
              <div class="col-lg-6" data-aos="fade-up">


                <h3 class="resume-title">Interests</h3>
                <div class="resume-item">
                  <h4>Professional</h4>
                  <p><em>Backend development, full stack development. </em></p>
                  </div>
                <div class="resume-item">
                  <h4>Personal</h4>
                  <p><em>Science, programming, rock climbing, history, photagraphy.</em></p>
                  </div>
            

                <h3 class="resume-title">Languages</h3>
                <div class="resume-item">
                  <h4>Python</h4>
                  <p><em> OOP, multi-processing/threading, exception handling, logging, virtual environments, basic scripting. Introductory exposure to Django, beautiful soup, symbolic calculations with sympy.</em></p>
                  </div>
                <div class="resume-item">
                  <h4>Java</h4>
                  <p><em> Generics, OOP, exception handling. Introductory exposure to Maven, Gradle, Android app development.</em></p>
                  </div>
                <div class="resume-item">
                  <h4>JavaScript/Typescript/Node.js</h4>
                  <p><em> Async calls, front end scripts, Express, Mongoose</em></p>
                  </div> 
                <div class="resume-item">
                  <h4>C, C++, SQL</h4>
                  <p><em>Exposure in academic coursework.</em></p>
                  </div> 

                  <h3 class="resume-title">Technologies and concepts</h3>
                  <div class="resume-item">
                    <h4>Databases</h4>
                    <p><em>MongoDB (noSQL), Mongoose ODM, Postgress(SQL), Django ORM, Knex.js query builder.</em></p>
                    </div>
                  <div class="resume-item">
                    <h4>Backend</h4>
                    <p><em> REST APIs, web applications, deployment (Heroku). Introductory exposure to AWS S3.</em></p>
                    </div>
                  <div class="resume-item">
                    <h4>Frontend</h4>
                    <p><em> HTML, CSS, Bootstrap, dynamic scripts, templates, DOM manipulation, introductory React.</em></p>
                    </div> 
                  <div class="resume-item">
                    <h4>Testing</h4>
                    <p><em>Unit tests (pyTest, Junit), brief exposure to Selenium.</em></p>
                    </div> 
                  <div class="resume-item">
                    <h4>Editors/IDEs</h4>
                    <p><em>IntelliJ, Eclispe, Visual Studio, PyCharm, Jupyter notebooks.</em></p>
                  </div> 
                  <div class="resume-item">
                    <h4>General</h4>
                    <p><em>Git, Git flow, BASH/Linux basics, regex, UML class diagrams, Design patterns, Slack. Introductory exposure to Docker.</em></p>
                  </div> 
      




       
              </div>
              <div class="col-lg-6" data-aos="fade-up" data-aos-delay="100">


                <h3 class="resume-title">Education</h3>
                <div class="resume-item">
                  <h4>Oregon State and Santa Barbara City College</h4>
                  <h5>Sept 2019 - June 2021</h5>
  
                  <ul>
                    <li><strong>Coursework</strong>: Includes Data Structures, Algorithms, Android Programming, Design Patterns, Computer
                    Architecture & Assembly Language, Databases, Discrete Math, Software Engineering, Programming
                    Languages, Linear Algebra.</li>
                    <li><strong>Activities</strong>: Involvement in competitive programming and computer science clubs.</li>
                    <li><strong>Competitions</strong>: ICPC Southern CA regional 2019.</li>
            
                  </ul>
                </div>
                <div class="resume-item">
                  <h4>Hamline University, BS Chemistry</h4>
                  <h5>Sept 2007 - May 20111</h5>
  
                  <ul>
                    <li><strong>GPA</strong>: 3.53 / Chemistry 3.65.</li>
                    <li><strong>Awards</strong>: American Institute of Chemists Award, Beggs Scholarship, Carter Scholarship: for a “chemistry
                    major with an outstanding record”, Mitsch Scholarship, Hamline Honor's Scholarship.</li>
                    <li><strong>Activities</strong>: Elected to President and PR positions for school’s rock climbing club.</li>            
               
                  </ul>
                </div>
  

                
                <h3 class="resume-title">Selected Professional Experience</h3>
                <div class="resume-item">
                  <h4>Contract Backend Development Engineer</h4>
                  <h5>Carterhaugh, Mar 2022 – June 2022</h5>
                  
                  <p><em>Development of internal tools and additions to code base shared between projects. Scraping and
                    transforming data using external services. Typescript backend, React Frontend, Postgress SQL, Lerna
                    versioning system.</p>
                </div>
                <div class="resume-item">
                  <h4>Processing Chemist</em></h4>
                  <h5>Nitto Denko Technical Corporation, May 2013 - Aug 2018</h5>
                  <h6><em></em></h6>
                  <p><em>Development of intellectual property for international team primarily focused on aqueous and gaseous
                    filtration media and applications of graphene oxide, leading to several patents.</em></p>
                  <p><em>Formulation and characterization of thin film nanocomposites, antimicrobial materials, and photocatalysts.</em></p>
                  </div>
              </div>
            </div>
    
          </div>
        </section><!-- End Resume Section -->
{% endblock %}

personal_webpage/portfolio/templates/portfolio/portfolio_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/4.5.0/darkly/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href={% static "portfolio.css" %}>
    <!-- <link rel="stylesheet" type="text/css" href={% static "home_site.css" %}> -->
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css">
    
  </head>
  <body >

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'portfolio:about' %}">About Me</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio:contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'portfolio:projects' %}">Projects</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/JREricson/"><i class="lab la-github"></i>Github</a> 
              <!-- TODO - add github logo -->
            </li>
          </ul>
          <ul class="navbar-nav  ms-auto">
            <li class="nav-item">
              <a class="nav-link" href="#">My Website</a>
            </li>
          </ul>
        </div>
      </div>

    </nav>



</nav>

{% if messages %}
{% for message in messages %}
  <div class="alert alert-{{ message.tags }}">
    {{ message }}
  </div>
{% endfor %}
{% endif %}





    

    {% block content %}{% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

personal_webpage/portfolio/templates/portfolio/portfolio_contact.html
{% extends "portfolio/portfolio_base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h1 class="page-heading">Contact John Ericson</h1>

<form class="site-form" method="POST" action="." novalidate>
  {% csrf_token %}
  <fieldset class="form-group">
    <legend class="border-bottom mb-4">Log In</legend>
    {{ form|crispy }}
  </fieldset>
  <div class="form-group">
    <button class="btn btn-outline-info form-control" type="submit">Send email</button>
  </div>



</form>


{% endblock %}

personal_webpage/portfolio/templates/portfolio/portfolio_home.html
{% extends "portfolio/portfolio_base.html" %}

{% block content %}
  <h1>Home Page</h1>
  <h2>Page is under construction</h2>
  {% for project in projects %} 
  <!-- check for featured items -->

    <p>{{ project.title }}</p>
    <p> {{ project.description}}</p>
    <p> {{project.github }}</p>
    <p> {{ project.website}}</p>
    <p> {{project.img_url }}</p>
    <p> {{project.date_posted |date:"Y, F j"}}</p>
    <br>
  {% endfor %}

{% endblock %}

personal_webpage/portfolio/templates/portfolio/portfolio_project.html
{% extends "portfolio/portfolio_base.html" %}
{% load markdownify %}
{% block content %}
<div class="container-fluid project-desc-container">


    <h1 class="page-heading">{{object.title}}</h1>

    {% if object.website or object.github %}
        <h2>External Links  </h2>
    {% endif %}

  
    {% if object.github%}
        <p><Strong><i class="lab la-github"></i>Github Repo: </Strong> <a href="{{object.website}}">{{object.github}}</a></p>
    {% endif %}

    {% if object.website%}
        <p><Strong><i class="las la-external-link-square-alt"></i>Live website: </Strong> <a href="{{object.website}}">{{object.website}}</a></p> 
    {% endif %}


    {{object.description|markdownify}}


</div>




{% endblock %}

personal_webpage/portfolio/templates/portfolio/portfolio_projects.html
{% extends "portfolio/portfolio_base.html" %}
{% load markdownify %}
{% block content %}
<h1 class="page-heading">Examples of Completed Projects</h1>



<div class="container">
  {% for project in projects %}
  <div class="card card-item project-card">
    <h2 class="project-title"><strong>{{project.title}}</strong></h2>
    <h4 class="project-desc-short">{{project.description_short|markdownify}}</h4>
    <img class="project-img" src="{{project.img_url}}"></img>

    {% if project.github  %}
    <h4 class="project-github"><strong> <i class="lab la-github"></i> Github Repo: </strong><a href="{{project.github}}" >{{project.github}}</a> </h4>
    {% endif %}

    <!-- <h4 class="project-website">Project Website: <a href="{{project.website}}" >{{project.website}}</a></h4> -->
    {% if project.technology  %}
    <h4 class="project-tech"><strong><i class="las la-code"></i>Technologies: </strong>{{project.technology}} </h4>
    {% endif %}
    {% if project.concepts  %}
    <h4 class="project-concepts"><strong><i class="las la-lightbulb"></i>Concepts: </strong>{{project.concepts}} </h4>
    {% endif %}



 

    <!-- <div class="btn-group inline pull-left" > 
   <button class="btn btn-xs inline">tag1</button>
   <button class="btn btn-xs">tag2</button>
   <button class="btn btn-xs">tag3</button>
    </div> -->

    <a class="btn btn-info" href="{%url 'portfolio:project' project.id %}">See project</a>
    <br>

  </div>
  {% endfor %}
</div>

    

  <br>
  {% if is_paginated %}

  {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
      <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
  {% endif %}

{% endif %}


{% endblock %}